Fix warning using ERR_FAIL_INDEX on unsigned int
This method starting being used in 83af0497db32f1015c8b7cb9b2fa9838ad6dfbe5,
which now triggers this warning from GCC 10:
```
./core/error_macros.h:151:25: error: comparison of unsigned expression in '< 0' is always false [-Werror=type-limits]
```