Object: Remove error on disconnect of locked signals
According to https://github.com/godotengine/godot/commit/45d3ba1f5c9f56708e1870ba86b386d811fb4752#commitcomment-36651823
and as confirmed by @reduz, this seems not to be necessary now that we
copy-on-write.

This triggered freeze scenarios in cases where a node would be deleted
while being used as a target in a signal emission.

Fixes #34650.
Fixes #34769.

Now those two errors go back to reporting:
```
ERROR: emit_signal: Condition ' !target ' is true. Continuing..:
   At: core/object.cpp:1191.
```